Devops:
  Gitlab:
    Host: 127.0.0.1
    Password: chenhao2
    Port: "70"
    User: root
    Version: ee
  Pipelines:
  - Ci: devops/devops/-/raw/master/java.yml
    Pipeline: java
    Template: Spring
  - Ci: devops/devops/-/raw/master/python.yml
    Pipeline: python
  - Ci: devops/devops/-/raw/master/nodejs.yml
    Pipeline: nodejs
